### PR TITLE
Rc first branch

### PR DESCRIPTION
**Pull request by rusll-repo**
add tests for balanced_brackets

### CODE REVIEW

**Review by Stan575 — APPROVED** [review]
Good job!

**Comment by rusll-repo** [comment]
> Good job!

Thanks

**Comment by Stan575** [comment]
@rusll-repo can you delete asserts from https://github.com/Stan575/westside-tp/blob/rc-first-branch/unit/src/balanced_brackets.py

**Comment by rusll-repo** [comment]
> @rusll-repo can you delete asserts from https://github.com/Stan575/westside-tp/blob/rc-first-branch/unit/src/balanced_brackets.py

Done

**Pull request merged**
