### PR TITLE
SA-Test: GD_HP002

### PR DESCRIPTION
**Pull request by Stan575**
Add test for header Mint button on home page
[Test case GD_HP002: Header 'Mint' button](https://docs.google.com/spreadsheets/d/1SGYka3qzeakFe3bu5CqAD1On02wvJMQjI0XkuJCHLr0/edit#gid=1503834326)

### CODE REVIEW

**Comment by rusll-repo** [comment]
Can rename filename on test_home_page

**Comment by Stan575** [comment]
> Can rename filename on test_home_page



> Can rename filename on test_home_page

Yeah, good point

**Comment by Stan575** [comment]
> Can rename filename on test_home_page



> Can rename filename on test_home_page

Yeah, good point

**Review by val-kan — APPROVED** [review]
looks good!

**Comment by rusll-repo** [comment]
It looks better.

**Pull request merged**
